USE DATABASE SPARQ_CHALLENGE;
USE SCHEMA SILVER;

CREATE FILE FORMAT IF NOT EXISTS FF_CSV_DIM
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  TRIM_SPACE = TRUE
  EMPTY_FIELD_AS_NULL = TRUE
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

CREATE TABLE IF NOT EXISTS DIM_POLICE_FORCE (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_ACCIDENT_SEVERITY (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_DAY_OF_WEEK (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_LOCAL_AUTHORITY_DISTRICT (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_LOCAL_AUTHORITY_HIGHWAY (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_1ST_ROAD_CLASS (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_ROAD_TYPE (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_SPEED_LIMIT (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_JUNCTION_DETAIL (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_JUNCTION_CONTROL (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_2ND_ROAD_CLASS (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_PED_CROSS_HUMAN (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_PED_CROSS_PHYSICAL (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_LIGHT_CONDITIONS (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_WEATHER (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_ROAD_SURFACE (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_SPECIAL_CONDITIONS_AT_SITE (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_CARRIAGEWAY_HAZARDS (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_URBAN_RURAL (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_POLICE_OFFICER_ATTEND (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_VEHICLE_TYPE (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_TOWING_AND_ARTICULATION (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_VEHICLE_MANOEUVRE (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_VEHICLE_LOCATION (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_JUNCTION_LOCATION (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_SKIDDING_AND_OVERTURNING (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_HIT_OBJECT_IN_CARRIAGEWAY (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_VEH_LEAVING_CARRIAGEWAY (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_HIT_OBJECT_OFF_CARRIAGEWAY (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_1ST_POINT_OF_IMPACT (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_WAS_VEHICLE_LEFT_HAND_DRIVE (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_JOURNEY_PURPOSE (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_SEX_OF_DRIVER (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_AGE_BAND (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_VEHICLE_PROPULSION_CODE (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_CASUALTY_CLASS (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_SEX_OF_CASUALTY (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_AGE_OF_CASUALTY (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_CASUALTY_SEVERITY (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_PED_LOCATION (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_PED_MOVEMENT (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_CAR_PASSENGER (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_BUS_PASSENGER (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_PED_ROAD_MAINTENANCE_WORKER (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_CASUALTY_TYPE (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_IMD_DECILE (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

CREATE TABLE IF NOT EXISTS DIM_HOME_AREA_TYPE (
  "CODE" VARCHAR,
  "LABEL" VARCHAR
);

TRUNCATE TABLE IF EXISTS DIM_POLICE_FORCE;

COPY INTO DIM_POLICE_FORCE
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_POLICE_FORCE.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_ACCIDENT_SEVERITY;

COPY INTO DIM_ACCIDENT_SEVERITY
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_ACCIDENT_SEVERITY.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_DAY_OF_WEEK;

COPY INTO DIM_DAY_OF_WEEK
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_DAY_OF_WEEK.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_LOCAL_AUTHORITY_DISTRICT;

COPY INTO DIM_LOCAL_AUTHORITY_DISTRICT
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_LOCAL_AUTHORITY_DISTRICT.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_LOCAL_AUTHORITY_HIGHWAY;

COPY INTO DIM_LOCAL_AUTHORITY_HIGHWAY
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_LOCAL_AUTHORITY_HIGHWAY.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_1ST_ROAD_CLASS;

COPY INTO DIM_1ST_ROAD_CLASS
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_1ST_ROAD_CLASS.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_ROAD_TYPE;

COPY INTO DIM_ROAD_TYPE
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_ROAD_TYPE.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_SPEED_LIMIT;

COPY INTO DIM_SPEED_LIMIT
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_SPEED_LIMIT.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_JUNCTION_DETAIL;

COPY INTO DIM_JUNCTION_DETAIL
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_JUNCTION_DETAIL.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_JUNCTION_CONTROL;

COPY INTO DIM_JUNCTION_CONTROL
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_JUNCTION_CONTROL.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_2ND_ROAD_CLASS;

COPY INTO DIM_2ND_ROAD_CLASS
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_2ND_ROAD_CLASS.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_PED_CROSS_HUMAN;

COPY INTO DIM_PED_CROSS_HUMAN
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_PED_CROSS_HUMAN.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_PED_CROSS_PHYSICAL;

COPY INTO DIM_PED_CROSS_PHYSICAL
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_PED_CROSS_PHYSICAL.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_LIGHT_CONDITIONS;

COPY INTO DIM_LIGHT_CONDITIONS
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_LIGHT_CONDITIONS.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_WEATHER;

COPY INTO DIM_WEATHER
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_WEATHER.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_ROAD_SURFACE;

COPY INTO DIM_ROAD_SURFACE
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_ROAD_SURFACE.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_SPECIAL_CONDITIONS_AT_SITE;

COPY INTO DIM_SPECIAL_CONDITIONS_AT_SITE
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_SPECIAL_CONDITIONS_AT_SITE.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_CARRIAGEWAY_HAZARDS;

COPY INTO DIM_CARRIAGEWAY_HAZARDS
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_CARRIAGEWAY_HAZARDS.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_URBAN_RURAL;

COPY INTO DIM_URBAN_RURAL
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_URBAN_RURAL.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_POLICE_OFFICER_ATTEND;

COPY INTO DIM_POLICE_OFFICER_ATTEND
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_POLICE_OFFICER_ATTEND.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_VEHICLE_TYPE;

COPY INTO DIM_VEHICLE_TYPE
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_VEHICLE_TYPE.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_TOWING_AND_ARTICULATION;

COPY INTO DIM_TOWING_AND_ARTICULATION
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_TOWING_AND_ARTICULATION.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_VEHICLE_MANOEUVRE;

COPY INTO DIM_VEHICLE_MANOEUVRE
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_VEHICLE_MANOEUVRE.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_VEHICLE_LOCATION;

COPY INTO DIM_VEHICLE_LOCATION
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_VEHICLE_LOCATION.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_JUNCTION_LOCATION;

COPY INTO DIM_JUNCTION_LOCATION
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_JUNCTION_LOCATION.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_SKIDDING_AND_OVERTURNING;

COPY INTO DIM_SKIDDING_AND_OVERTURNING
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_SKIDDING_AND_OVERTURNING.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_HIT_OBJECT_IN_CARRIAGEWAY;

COPY INTO DIM_HIT_OBJECT_IN_CARRIAGEWAY
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_HIT_OBJECT_IN_CARRIAGEWAY.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_VEH_LEAVING_CARRIAGEWAY;

COPY INTO DIM_VEH_LEAVING_CARRIAGEWAY
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_VEH_LEAVING_CARRIAGEWAY.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_HIT_OBJECT_OFF_CARRIAGEWAY;

COPY INTO DIM_HIT_OBJECT_OFF_CARRIAGEWAY
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_HIT_OBJECT_OFF_CARRIAGEWAY.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_1ST_POINT_OF_IMPACT;

COPY INTO DIM_1ST_POINT_OF_IMPACT
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_1ST_POINT_OF_IMPACT.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_WAS_VEHICLE_LEFT_HAND_DRIVE;

COPY INTO DIM_WAS_VEHICLE_LEFT_HAND_DRIVE
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_WAS_VEHICLE_LEFT_HAND_DRIVE.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_JOURNEY_PURPOSE;

COPY INTO DIM_JOURNEY_PURPOSE
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_JOURNEY_PURPOSE.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_SEX_OF_DRIVER;

COPY INTO DIM_SEX_OF_DRIVER
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_SEX_OF_DRIVER.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_AGE_BAND;

COPY INTO DIM_AGE_BAND
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_AGE_BAND.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_VEHICLE_PROPULSION_CODE;

COPY INTO DIM_VEHICLE_PROPULSION_CODE
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_VEHICLE_PROPULSION_CODE.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_CASUALTY_CLASS;

COPY INTO DIM_CASUALTY_CLASS
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_CASUALTY_CLASS.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_SEX_OF_CASUALTY;

COPY INTO DIM_SEX_OF_CASUALTY
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_SEX_OF_CASUALTY.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_AGE_OF_CASUALTY;

COPY INTO DIM_AGE_OF_CASUALTY
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_AGE_OF_CASUALTY.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_CASUALTY_SEVERITY;

COPY INTO DIM_CASUALTY_SEVERITY
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_CASUALTY_SEVERITY.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_PED_LOCATION;

COPY INTO DIM_PED_LOCATION
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_PED_LOCATION.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_PED_MOVEMENT;

COPY INTO DIM_PED_MOVEMENT
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_PED_MOVEMENT.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_CAR_PASSENGER;

COPY INTO DIM_CAR_PASSENGER
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_CAR_PASSENGER.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_BUS_PASSENGER;

COPY INTO DIM_BUS_PASSENGER
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_BUS_PASSENGER.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_PED_ROAD_MAINTENANCE_WORKER;

COPY INTO DIM_PED_ROAD_MAINTENANCE_WORKER
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_PED_ROAD_MAINTENANCE_WORKER.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_CASUALTY_TYPE;

COPY INTO DIM_CASUALTY_TYPE
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_CASUALTY_TYPE.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_IMD_DECILE;

COPY INTO DIM_IMD_DECILE
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_IMD_DECILE.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;

TRUNCATE TABLE IF EXISTS DIM_HOME_AREA_TYPE;

COPY INTO DIM_HOME_AREA_TYPE
FROM @SPARQ_CHALLENGE.BRONZE.internal_stage/variablelookup/dimensions/DIM_HOME_AREA_TYPE.csv
FILE_FORMAT = (FORMAT_NAME = 'FF_CSV_DIM')
FORCE = TRUE;